server:
  port: 8076
  forward-headers-strategy: framework
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-rabbitmq-samples
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    bindings:
      customer:
        queue: customer
        dlq: customer.dlq
        delay-in-ms: 5000
        exchange: customer.exchange
        routing-key: customer.routingKey

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

info:
  name: ${spring.application.name}
  description: Spring Rabbitmq Demo
  environment: ${spring.profiles.active}
  version: 0.0.1

springdoc:
  version: '@springdoc.version@'
  api-docs:
    version: openapi_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  cache:
    disabled: true